baseURL: "https://stevenchu.com"
languageCode: "en-us"
title: "Hugo Novela"
pygmentsstyle: 'monokai'
metaDataFormat: yaml

# Theme settings
# theme: novela
module:
  imports:
    - path: "github.com/forestryio/hugo-theme-novela"
paginate: 18
social:
  twitter: "#"
  github: "#"
  instagram: "#"
  linkedin: "#"
  dribbble: "#"
  youtube: "#"
taxonomies:
  author: authors
